export const apiEndpointPaths = {
  authenticationBase: "/api/auth",
  authenticationSession: "/api/auth/get-session",
  customerProfile: "/api/v1/customer-profile",
  customerSavedAddresses: "/api/v1/customer-profile/addresses",
  customerSavedAddress: (addressId: string) => `/api/v1/customer-profile/addresses/${addressId}`,
  customerProfileMediaUploadSignatures: "/api/v1/customer-profile/media/upload-signatures",
  customerProfileMediaConfirmations: "/api/v1/customer-profile/media/confirmations",
  customerProfileImage: "/api/v1/customer-profile/media/profile-image",
  providerProfile: "/api/v1/provider-profile",
  providerProfileMediaUploadSignatures: "/api/v1/provider-profile/media/upload-signatures",
  providerProfileMediaConfirmations: "/api/v1/provider-profile/media/confirmations",
  providerProfileMediaAsset: (mediaAssetId: string) => `/api/v1/provider-profile/media/${mediaAssetId}`,
  profileUsername: "/api/v1/profile/username",
  administrationProviderProfiles: "/api/v1/administration/provider-profiles",
  administrationProviderProfile: (providerProfileId: string) => `/api/v1/administration/provider-profiles/${providerProfileId}`,
  administrationOverview: "/api/v1/administration/overview",
  administrationUsers: "/api/v1/administration/users",
  administrationUser: (userId: string) => `/api/v1/administration/users/${userId}`,
  administrationUserRoleChanges: (userId: string) => `/api/v1/administration/users/${userId}/role-changes`,
  administrationUserBanActions: (userId: string) => `/api/v1/administration/users/${userId}/ban-actions`,
  administrationUserAccountStatusActions: (userId: string) =>
    `/api/v1/administration/users/${userId}/account-status-actions`,
  administrationAuditEvents: "/api/v1/administration/audit-events",
  administrationServiceCategories: "/api/v1/administration/service-categories",
  administrationServiceCategory: (categoryId: string) => `/api/v1/administration/service-categories/${categoryId}`,
  administrationProviderReviewActions: (providerProfileId: string) =>
    `/api/v1/administration/provider-profiles/${providerProfileId}/review-actions`,
} as const;
